--(4016 rows affected)

DECLARE @MODIFIED_BY NVARCHAR(50) = 'POSTMIGR_EXT_AUD_003';
DECLARE @MODIFIED DATETIME = GETDATE();

WITH WLMS AS (
---
SELECT NULL AS EXTERNAL_AUDIT_ID, NULL AS CONTRACT_NUMBER, NULL AS FISCAL_YEAR, NULL AS INSTITUTION_CODE, NULL AS OPINION_CODE, NULL AS PRODUCT_STATUS_CODE, NULL AS MIGRATED_DUE_DATE, NULL AS AUDIT_TYPE),

WMLS_TRANSFORMED AS (
SELECT EXTERNAL_AUDIT_ID
	,CONTRACT_NUMBER
	,FISCAL_YEAR
	,INSTITUTION_CODE
	,OPINION_CODE
	,PRODUCT_STATUS_CODE
	,MIGRATED_DUE_DATE
	,CASE LEFT(AUDIT_TYPE, 4)
		WHEN 'BORR' THEN 'OEAFS'
		WHEN 'EXEC' THEN 'EAFS'
		WHEN 'OTHE' THEN 'OP'
		WHEN 'PROJ' THEN 'PAFS'
	END AS AUDIT_TYPE
FROM WLMS),

AUDIT_TYPE AS (
SELECT CONVERGENCE_MASTER_DATA_ID AS AUDIT_TYPE_ID
	,CODE AS AUDIT_TYPE_CODE
	,NAME_EN AS AUDIT_TYPE_NAME
FROM CONVERGENCE_MASTER_TYPE
JOIN CONVERGENCE_MASTER_DATA ON FK_CONVERGENCE_MASTER_TYPE_ID = CONVERGENCE_MASTER_TYPE_ID
WHERE TYPE = 'EXTERNAL_AUDIT_TYPE')

UPDATE EXTERNAL_AUDIT
SET FK_AUDIT_TYPE_ID = AUDIT_TYPE.AUDIT_TYPE_ID
	,MODIFIED = @MODIFIED
	,MODIFIED_BY = @MODIFIED_BY
FROM WMLS_TRANSFORMED
JOIN AUDIT_TYPE ON AUDIT_TYPE.AUDIT_TYPE_CODE = WMLS_TRANSFORMED.AUDIT_TYPE
WHERE EXTERNAL_AUDIT.EXTERNAL_AUDIT_ID = WMLS_TRANSFORMED.EXTERNAL_AUDIT_ID
