--(4016 rows affected)

DECLARE @MODIFIED_BY NVARCHAR(50) = 'POSTMIGR_EXT_AUD_003';
DECLARE @MODIFIED DATETIME = GETDATE();

WITH WLMS AS (
---
SELECT NULL AS CONTRACT_NUMBER, NULL AS FISCAL_YEAR, NULL AS INSTITUTION_CODE, NULL AS OPINION_CODE, NULL AS PRODUCT_STATUS_CODE, NULL AS MIGRATED_DUE_DATE, NULL AS AUDIT_TYPE),

WMLS_TRANSFORMED AS (
SELECT CONTRACT_NUMBER
	,FISCAL_YEAR
	,INSTITUTION_CODE
	,OPINION_CODE
	,PRODUCT_STATUS_CODE
	,MIGRATED_DUE_DATE
	,CASE LEFT(AUDIT_TYPE, 4)
		WHEN 'BORR' THEN 'OEAFS'
		WHEN 'EXEC' THEN 'EAFS'
		WHEN 'OTHE' THEN 'OP'
		WHEN 'PROJ' THEN 'PAFS'
	END AS AUDIT_TYPE
FROM WLMS),

AUDIT_TYPE AS (
SELECT CONVERGENCE_MASTER_DATA_ID AS AUDIT_TYPE_ID
	,CODE AS AUDIT_TYPE_CODE
	,NAME_EN AS AUDIT_TYPE_NAME
FROM CONVERGENCE_MASTER_TYPE
JOIN CONVERGENCE_MASTER_DATA ON FK_CONVERGENCE_MASTER_TYPE_ID = CONVERGENCE_MASTER_TYPE_ID
WHERE TYPE = 'EXTERNAL_AUDIT_TYPE'),

CONV AS (
SELECT EXTERNAL_AUDIT_ID
	,CONTRACT_NUMBER
	,FISCAL_YEAR
	,ISNULL(ACRNM, 'NULL') AS INSTITUTION_CODE
	,ISNULL(OPINION.CODE, 'NULL') AS OPINION_CODE
	,ISNULL(PRODUCT_STATUS.CODE, 'NULL') AS PRODUCT_STATUS_CODE
	,ISNULL(CONVERT(varchar, CONVERT(datetime, MIGRATED_DUE_DATE), 20), 'NULL') AS MIGRATED_DUE_DATE
	,ROW_NUMBER() OVER(PARTITION BY CONTRACT_NUMBER
		,FISCAL_YEAR
		,ACRNM
		,OPINION.CODE
		,PRODUCT_STATUS.CODE
		,MIGRATED_DUE_DATE ORDER BY EXTERNAL_AUDIT_ID) AS RN
	,COUNT(*) OVER(PARTITION BY CONTRACT_NUMBER
		,FISCAL_YEAR
		,ACRNM
		,OPINION.CODE
		,PRODUCT_STATUS.CODE
		,MIGRATED_DUE_DATE) AS CNT
FROM EXTERNAL_AUDIT
JOIN CONTRACT ON CONTRACT_ID = FK_CONTRACT_ID
LEFT JOIN INSTITUTION ON INSTITUTION_ID = FK_AUDITOR_ID
LEFT JOIN CONVERGENCE_MASTER_DATA AS OPINION ON OPINION.CONVERGENCE_MASTER_DATA_ID = FK_OPINION_ID
LEFT JOIN CONVERGENCE_MASTER_DATA AS PRODUCT_STATUS ON PRODUCT_STATUS.CONVERGENCE_MASTER_DATA_ID = FK_PRODUCT_STATUS_ID
WHERE EXTERNAL_AUDIT.CREATED_BY IN ('MIGR_EXT_AUD', 'POSTMIGR_EXT_AUD_002'))

UPDATE EXTERNAL_AUDIT
SET FK_AUDIT_TYPE_ID = AUDIT_TYPE.AUDIT_TYPE_ID
	,MODIFIED = @MODIFIED
	,MODIFIED_BY = @MODIFIED_BY
FROM WMLS_TRANSFORMED
JOIN AUDIT_TYPE ON AUDIT_TYPE.AUDIT_TYPE_CODE = WMLS_TRANSFORMED.AUDIT_TYPE
JOIN CONV ON WMLS_TRANSFORMED.CONTRACT_NUMBER = CONV.CONTRACT_NUMBER
	AND WMLS_TRANSFORMED.FISCAL_YEAR = CONV.FISCAL_YEAR
	AND WMLS_TRANSFORMED.INSTITUTION_CODE = CONV.INSTITUTION_CODE
	AND WMLS_TRANSFORMED.OPINION_CODE = CONV.OPINION_CODE
	AND WMLS_TRANSFORMED.PRODUCT_STATUS_CODE = CONV.PRODUCT_STATUS_CODE
	AND WMLS_TRANSFORMED.MIGRATED_DUE_DATE = CONV.MIGRATED_DUE_DATE
	AND (CONV.CNT = 1 
		OR (CONV.CNT = 2 
			AND LEFT(WMLS_TRANSFORMED.AUDIT_TYPE, 4) = 
				CASE CONV.RN 
					WHEN 1 THEN 'PROJ' 
					WHEN 2 THEN 'EXEC' 
				END))
WHERE EXTERNAL_AUDIT.EXTERNAL_AUDIT_ID = CONV.EXTERNAL_AUDIT_ID
