--(9 rows affected)
--(568 rows affected)
--(1 row affected)

DECLARE @MODIFIED_BY NVARCHAR(50) = 'POSTMIGR_EXT_AUD_004';
DECLARE @MODIFIED DATETIME = GETDATE();

UPDATE EXTERNAL_AUDIT
SET FK_AUDIT_TYPE_ID = (SELECT CONVERGENCE_MASTER_DATA_ID FROM CONVERGENCE_MASTER_DATA WHERE CODE = 'PAFS')
	,MODIFIED = @MODIFIED
	,MODIFIED_BY = @MODIFIED_BY
WHERE EXTERNAL_AUDIT_ID IN 
(3858
,2256
,743
,211
,2345
,2505
,2504
,3277
,2155);

UPDATE EXTERNAL_AUDIT
SET AUDITOR_TYPE = 'Supreme Audit Institutions'
	,MODIFIED = @MODIFIED
	,MODIFIED_BY = @MODIFIED_BY
FROM EXTERNAL_AUDIT
JOIN INSTITUTION ON INSTITUTION.INSTITUTION_ID = EXTERNAL_AUDIT.FK_AUDITOR_ID
WHERE EXTERNAL_AUDIT.CREATED_BY IN ('MIGR_EXT_AUD', 'POSTMIGR_EXT_AUD_002')
	AND EXTERNAL_AUDIT.AUDITOR_TYPE != 'Supreme Audit Institutions'
	AND INSTITUTION.ACRNM IN 
('AR-AGN'
,'AR-TCBS'
,'AR-TCME'
,'BA-AG'
,'BH-AG'
,'BR-BR-TCU'
,'BR-SFC'
,'BR-TBBH'
,'BR-TBPR'
,'BR-TCDF'
,'BR-TCE - MA'
,'BR-TCEAM'
,'BR-TCE-CE'
,'BR-TCEMR'
,'BR-TCE-MU PARA'
,'BR-TCE-PB'
,'BR-TCESE'
,'BR-TCMBA'
,'BR-TCMRJ'
,'BR-TCOMTAS.ES'
,'BR-TCONTAS'
,'BR-TCPA'
,'BR-TCPB'
,'BR-TCRG'
,'BR-TCSC'
,'BR-TCTOCAN'
,'CH-CGR'
,'CR-CGR'
,'GY-AG'
,'HO-CGR'
,'JA-AG'
,'TT-AG'
,'UR-TC');

IF NOT EXISTS(SELECT ACRNM FROM INSTITUTION WHERE ACRNM = 'GU-AA PINEDA')
BEGIN
	INSERT INTO INSTITUTION (ACRNM
		,NM
		,INSTUT_TYP
		,AUDITOR_TYPE
		,ADDR_LINE_ONE
		,ADDR_LINE_TWO
		,CITY
		,ZIP_CD
		,PHN_NUM
		,WEBSITE
		,FK_COUNTRY_ID
		,FK_INSTITUTION_TYPE_ID
		,FK_VALIDATION_STAGE_ID
		,CREATED
		,CREATED_BY)
	VALUES ('GU-AA PINEDA'
		,'Auditores y Asesores Sergio Pineda y Asociados, S. A'
		,'EXTERNAL AUDITORS'
		,'Independent Audit Firms'
		,'Avenida Reforma 9-55 zona 10'
		,'Edificio Reforma 10 5to. Of. 506'
		,'Guatemala'
		,'01010'
		,'+502 2324 3800'
		,'www.pinedacg.com/auditoria'
		,(SELECT CONVERGENCE_MASTER_DATA_ID FROM CONVERGENCE_MASTER_TYPE JOIN CONVERGENCE_MASTER_DATA ON FK_CONVERGENCE_MASTER_TYPE_ID = CONVERGENCE_MASTER_TYPE_ID WHERE TYPE = 'COUNTRY_ALL' AND CODE = 'GU')
		,(SELECT CONVERGENCE_MASTER_DATA_ID FROM CONVERGENCE_MASTER_TYPE JOIN CONVERGENCE_MASTER_DATA ON FK_CONVERGENCE_MASTER_TYPE_ID = CONVERGENCE_MASTER_TYPE_ID WHERE TYPE = 'INSTITUTION_TYPE' AND CODE = 'EA')
		,(SELECT CONVERGENCE_MASTER_DATA_ID FROM CONVERGENCE_MASTER_TYPE JOIN CONVERGENCE_MASTER_DATA ON FK_CONVERGENCE_MASTER_TYPE_ID = CONVERGENCE_MASTER_TYPE_ID WHERE TYPE = 'INSTITUTIONS_STATUS' AND CODE = 'INST_ACTV')
		,@MODIFIED
		,@MODIFIED_BY);
END
